Usage: mediamtx [<confpath>] [flags]

MediaMTX v1.21.1, linux, amd64

Arguments:
  [<confpath>]    path to a config file. The default is mediamtx.yml.

Flags:
  -h, --help                  Show context-sensitive help.
      --version               print version
      --check-version         check whether a new version is available
      --upgrade               upgrade executable to the latest version
      --validate-conf=path    check whether a configuration file is valid

